# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DairyCow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_id', models.IntegerField(default=0)),
                ('birth_date', models.DateField()),
                ('parity', models.IntegerField(default=1)),
                ('milk_yield', models.FloatField(default=7000)),
            ],
        ),
        migrations.CreateModel(
            name='DairyHerd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herd_size', models.IntegerField(default=0)),
                ('groups', models.IntegerField(default=3)),
            ],
        ),
    ]
