# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0002_auto_20160812_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='dairyherd',
            name='herd_name',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
